// Code generated by MockGen. DO NOT EDIT.
// Source: api.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	model "github.com/wearegravitylabs/ngnmarket-go/model"
)

// MockRemoteCalls is a mock of RemoteCalls interface.
type MockRemoteCalls struct {
	ctrl     *gomock.Controller
	recorder *MockRemoteCallsMockRecorder
}

// MockRemoteCallsMockRecorder is the mock recorder for MockRemoteCalls.
type MockRemoteCallsMockRecorder struct {
	mock *MockRemoteCalls
}

// NewMockRemoteCalls creates a new mock instance.
func NewMockRemoteCalls(ctrl *gomock.Controller) *MockRemoteCalls {
	mock := &MockRemoteCalls{ctrl: ctrl}
	mock.recorder = &MockRemoteCallsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRemoteCalls) EXPECT() *MockRemoteCallsMockRecorder {
	return m.recorder
}

// FindNGXCompany mocks base method.
func (m *MockRemoteCalls) FindNGXCompany(ctx context.Context, symbol string) (*model.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindNGXCompany", ctx, symbol)
	ret0, _ := ret[0].(*model.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindNGXCompany indicates an expected call of FindNGXCompany.
func (mr *MockRemoteCallsMockRecorder) FindNGXCompany(ctx, symbol interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindNGXCompany", reflect.TypeOf((*MockRemoteCalls)(nil).FindNGXCompany), ctx, symbol)
}

// FindUSTicker mocks base method.
func (m *MockRemoteCalls) FindUSTicker(ctx context.Context, symbol string) (*model.Ticker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUSTicker", ctx, symbol)
	ret0, _ := ret[0].(*model.Ticker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUSTicker indicates an expected call of FindUSTicker.
func (mr *MockRemoteCallsMockRecorder) FindUSTicker(ctx, symbol interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUSTicker", reflect.TypeOf((*MockRemoteCalls)(nil).FindUSTicker), ctx, symbol)
}

// GetNGXClosePriceOnOrBefore mocks base method.
func (m *MockRemoteCalls) GetNGXClosePriceOnOrBefore(ctx context.Context, symbol string, day time.Time) (model.PricePoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNGXClosePriceOnOrBefore", ctx, symbol, day)
	ret0, _ := ret[0].(model.PricePoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNGXClosePriceOnOrBefore indicates an expected call of GetNGXClosePriceOnOrBefore.
func (mr *MockRemoteCallsMockRecorder) GetNGXClosePriceOnOrBefore(ctx, symbol, day interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNGXClosePriceOnOrBefore", reflect.TypeOf((*MockRemoteCalls)(nil).GetNGXClosePriceOnOrBefore), ctx, symbol, day)
}

// GetNGXCompany mocks base method.
func (m *MockRemoteCalls) GetNGXCompany(ctx context.Context, symbol string) (*model.CompanyDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNGXCompany", ctx, symbol)
	ret0, _ := ret[0].(*model.CompanyDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNGXCompany indicates an expected call of GetNGXCompany.
func (mr *MockRemoteCallsMockRecorder) GetNGXCompany(ctx, symbol interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNGXCompany", reflect.TypeOf((*MockRemoteCalls)(nil).GetNGXCompany), ctx, symbol)
}

// GetNGXPriceChart mocks base method.
func (m *MockRemoteCalls) GetNGXPriceChart(ctx context.Context, symbol string, params *model.NGXChartParams) (*model.NGXChart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNGXPriceChart", ctx, symbol, params)
	ret0, _ := ret[0].(*model.NGXChart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNGXPriceChart indicates an expected call of GetNGXPriceChart.
func (mr *MockRemoteCallsMockRecorder) GetNGXPriceChart(ctx, symbol, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNGXPriceChart", reflect.TypeOf((*MockRemoteCalls)(nil).GetNGXPriceChart), ctx, symbol, params)
}

// GetUSClosePriceOnOrBefore mocks base method.
func (m *MockRemoteCalls) GetUSClosePriceOnOrBefore(ctx context.Context, symbol string, day time.Time) (model.PricePoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUSClosePriceOnOrBefore", ctx, symbol, day)
	ret0, _ := ret[0].(model.PricePoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUSClosePriceOnOrBefore indicates an expected call of GetUSClosePriceOnOrBefore.
func (mr *MockRemoteCallsMockRecorder) GetUSClosePriceOnOrBefore(ctx, symbol, day interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUSClosePriceOnOrBefore", reflect.TypeOf((*MockRemoteCalls)(nil).GetUSClosePriceOnOrBefore), ctx, symbol, day)
}

// GetUSPriceChart mocks base method.
func (m *MockRemoteCalls) GetUSPriceChart(ctx context.Context, symbol string, params *model.USChartParams) (*model.USChart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUSPriceChart", ctx, symbol, params)
	ret0, _ := ret[0].(*model.USChart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUSPriceChart indicates an expected call of GetUSPriceChart.
func (mr *MockRemoteCallsMockRecorder) GetUSPriceChart(ctx, symbol, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUSPriceChart", reflect.TypeOf((*MockRemoteCalls)(nil).GetUSPriceChart), ctx, symbol, params)
}

// GetUSTicker mocks base method.
func (m *MockRemoteCalls) GetUSTicker(ctx context.Context, symbol string) (*model.TickerDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUSTicker", ctx, symbol)
	ret0, _ := ret[0].(*model.TickerDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUSTicker indicates an expected call of GetUSTicker.
func (mr *MockRemoteCallsMockRecorder) GetUSTicker(ctx, symbol interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUSTicker", reflect.TypeOf((*MockRemoteCalls)(nil).GetUSTicker), ctx, symbol)
}

// ListAllNGXCompanies mocks base method.
func (m *MockRemoteCalls) ListAllNGXCompanies(ctx context.Context) ([]model.Company, model.Meta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllNGXCompanies", ctx)
	ret0, _ := ret[0].([]model.Company)
	ret1, _ := ret[1].(model.Meta)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListAllNGXCompanies indicates an expected call of ListAllNGXCompanies.
func (mr *MockRemoteCallsMockRecorder) ListAllNGXCompanies(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllNGXCompanies", reflect.TypeOf((*MockRemoteCalls)(nil).ListAllNGXCompanies), ctx)
}

// ListNGXCompanies mocks base method.
func (m *MockRemoteCalls) ListNGXCompanies(ctx context.Context, params *model.ListCompaniesParams) (*model.CompanyList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNGXCompanies", ctx, params)
	ret0, _ := ret[0].(*model.CompanyList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNGXCompanies indicates an expected call of ListNGXCompanies.
func (mr *MockRemoteCallsMockRecorder) ListNGXCompanies(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNGXCompanies", reflect.TypeOf((*MockRemoteCalls)(nil).ListNGXCompanies), ctx, params)
}

// ListNGXSymbols mocks base method.
func (m *MockRemoteCalls) ListNGXSymbols(ctx context.Context) (*model.CompanyIdentifiers, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNGXSymbols", ctx)
	ret0, _ := ret[0].(*model.CompanyIdentifiers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNGXSymbols indicates an expected call of ListNGXSymbols.
func (mr *MockRemoteCallsMockRecorder) ListNGXSymbols(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNGXSymbols", reflect.TypeOf((*MockRemoteCalls)(nil).ListNGXSymbols), ctx)
}

// ListUSSymbols mocks base method.
func (m *MockRemoteCalls) ListUSSymbols(ctx context.Context) (*model.TickerIdentifiers, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUSSymbols", ctx)
	ret0, _ := ret[0].(*model.TickerIdentifiers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUSSymbols indicates an expected call of ListUSSymbols.
func (mr *MockRemoteCallsMockRecorder) ListUSSymbols(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUSSymbols", reflect.TypeOf((*MockRemoteCalls)(nil).ListUSSymbols), ctx)
}

// ListUSTickers mocks base method.
func (m *MockRemoteCalls) ListUSTickers(ctx context.Context, params *model.ListTickersParams) (*model.TickerList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUSTickers", ctx, params)
	ret0, _ := ret[0].(*model.TickerList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUSTickers indicates an expected call of ListUSTickers.
func (mr *MockRemoteCallsMockRecorder) ListUSTickers(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUSTickers", reflect.TypeOf((*MockRemoteCalls)(nil).ListUSTickers), ctx, params)
}
